Numpy库的基础是ndarray(N-dimensional array，N维数组)对象。它是一种由同质元素组成的多维数组，元素数量是事先指定好的。

同质指的是几乎所有元素的类型和大小都相同。事实上，数据类型由另外一个叫做dtype(data-type,数据类型)的numpy对象来指定，每个ndarry只有一种dtype类型

## 一、 Numpy数组的特点

1、数组的维数和元素数量由数组的型（shape）来确定，数组的型由N个正整数组成的元组来指定，元组的每个元素对应每一维大小。
数组的维统称为轴（axes），轴的数量被称为秩（rank）

2、数组大小固定，也就是说，创建数组时一旦指定好大小，就不会再发生改变。这与Python的列表有所不同，列表的大小是可以改变的

In [1]:
import numpy as np

##### 一维数组

In [25]:
# 创建一个数组
a=np.array([1,2,3])  # a是一个1行3列的数组，即1*3,在维度中，1是可以忽略的，所有a是一维数组
print(a)
# 查看对象是否是ndarray
type(a)

[1 2 3]


numpy.ndarray

In [4]:
# 查看新建的ndarray属于哪种数据类型
a.dtype

dtype('int32')

In [5]:
# 查看数组对象的轴数axes
a.ndim  # a只有一维，x轴

1

In [6]:
# 查看数组对象的数组长度
a.size  # a总共有3个数字

3

In [7]:
# 查看数组的型
a.shape # 

(3,)

##### 多维数组

In [27]:
b=np.array([[1,2,3,4],[2,5,6,7],[4,6,7,2]])
# b是一个3行4列的数组，即3*4,这是2维的
print(b)

[[1 2 3 4]
 [2 5 6 7]
 [4 6 7 2]]


In [28]:
b.ndim  # b是由2维组成，x轴和y轴

2

In [29]:
b.size  # b总共有3*4=12个数字

12

In [30]:
b.shape # b是3行4列

(3, 4)

In [37]:
c=np.array([[[1,2,3,4],
             [3,4,5,6],
             [1,2,9,3]],
            
            [[7,6,7,4],
             [4,7,3,1],
             [4,7,8,4]]])
# c是一个2行2列但高为4的数组，即2*3*4，这是3维数组
c

array([[[1, 2, 3, 4],
        [3, 4, 5, 6],
        [1, 2, 9, 3]],

       [[7, 6, 7, 4],
        [4, 7, 3, 1],
        [4, 7, 8, 4]]])

In [38]:
c.ndim

3

In [39]:
c.shape

(2, 3, 4)

### 1、创建数组
最常使用array()函数，参数为单层或嵌套列表

In [40]:
d=np.array([[1,2,3],[4,5,6]]) # []为列表
d

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
e=np.array([[1,2,3,4],(4,5,6,7)])  #()为元组
e

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

#### 元组和列表的比较：
列表（list）：一般用来存放数据的列表，可以用来存放各式各样的数据，列表中存储数据是有序的。列表中的每条数据都有一个索引。第一条数据的索引为0，第二条数据的索引为1

元组（tuple）：元组中的数据一旦确定下来就不可以更改，不能进行添加，删除，修改等的操作，
可以认为元组是一个不可变的列表list

### 2、自带的数组创建方法

In [44]:
# zeros()函数能够生成shape参数指定维度信息、元素均为零的数组
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# ones()函数生成一个各元素均为1的数组
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# arange():根据传入的参数，按照特定规则，生成包含一个数值序列的数组。
np.arange(0,10) # 生成一个包含数字0到9的数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0,10,3)# 生成等间隔的在0-9之间的数组

array([0, 3, 6, 9])

arange(起始值，结束值，间距)；linspace（起始值，结束值，部分数）：部分数用来指定序列的起始和结尾两个数字所指定的范围分为几个部分

In [52]:
# reshape():按照指定的形状，把一维数组拆分为不同的形状
np.arange(0,12).reshape(3,4)# reshape(a,b):拆分为a行b列

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
# 使用numpy.random模块的random（）：生成随机数填充数组。
np.random.random(3)

array([0.23319082, 0.56927418, 0.59233473])

In [54]:
np.random.random((4,3))

array([[0.9348758 , 0.17768782, 0.49967682],
       [0.80355414, 0.12102894, 0.16854422],
       [0.13210143, 0.59736102, 0.48715222],
       [0.63358624, 0.40385451, 0.73381635]])

## 二、基本操作

#### 1、算术运算符
为数组加上或乘以一个标量。算术运算是元素级的。即它们只用于位置相同的元素之间，所得到的运算结果组成一个新的数组。

In [56]:
a=np.arange(5)
b=np.arange(4,9)
a,b

(array([0, 1, 2, 3, 4]), array([4, 5, 6, 7, 8]))

In [57]:
a+4

array([4, 5, 6, 7, 8])

In [58]:
a*4

array([ 0,  4,  8, 12, 16])

In [59]:
a+b

array([ 4,  6,  8, 10, 12])

In [60]:
a*b

array([ 0,  5, 12, 21, 32])

#### 2、矩阵积
dot()：表示两个矩阵之间的运算，即为矩阵积，它不是元素级的

In [69]:
A=np.arange(9).reshape(3,3)
B=np.arange(6,15).reshape(3,3)
np.dot(A,B)

array([[ 33,  36,  39],
       [114, 126, 138],
       [195, 216, 237]])

In [68]:
A*B

array([[  0,   7,  16],
       [ 27,  40,  55],
       [ 72,  91, 112]])

In [70]:
# 矩阵积的另一种写法：将dot()函数当做其中一个矩阵对象的方法
A.dot(B)

array([[ 33,  36,  39],
       [114, 126, 138],
       [195, 216, 237]])

#### 3、自增和自减运算符
使用+=或-=运算符

In [72]:
a=np.arange(4)
a+=2
a

array([2, 3, 4, 5])

In [76]:
a-=1
a

array([1, 2, 3, 4])

#### 4、通用函数
对数组中的各个元素逐一进行操作：通用函数分别处理输入数组的每个元素，生成的结果组成一个新的输出数组。输出数组的大小跟输入数组相同

sqrt():平方根； log():取对数； sin():求正弦

#### 5、聚合函数
对一组值（比如一个数组）进行操作，返回一个单一值作为结果的函数。

sum（）求和；count（）：计次；min（）；max（）；std（）；mean（）

#### 6、索引机制、切片和迭代方法

##### 6.1 索引机制
数据索引机制指的是用方括号[ ]加序号的形式应用单个数组元素。

一维数组

In [78]:
# 获取数组的单个元素，指定元素的索引即可
a=np.arange(10,16)
a[4]

14

In [81]:
# 获取多个元素，[]中传入多个索引值
a[[1,3,4]]

array([11, 13, 14])

二维数组，即矩阵索引

矩阵是由行和列组成的矩形数组，行和列用两条轴来定义，其中轴0用行表示，轴1用列表示。因此，二维数组的索引用一对值来表示：第一个值为行索引，第二个值为列索引。[行索引，列索引]

In [103]:
A=np.arange(10,19).reshape((3,3))
A[1,2]

15

##### 6.2 切片操作
切片操作是指抽取数组的一部分元素生成新数组。切片句法：把几个用冒号：隔开的数据置于方括号里。即[a:b]

一维数组

In [90]:
B=np.arange(10,16)
B

array([10, 11, 12, 13, 14, 15])

In [91]:
B[1:5]  # 指定起始元素的索引1和结束元素的索引5

array([11, 12, 13, 14])

In [87]:
B[1:5:2] # 在上面的元素中，每个一定数量的元素抽取一个。这里每隔一个元素抽取一个

array([11, 13])

In [92]:
# 切片时，省去起始值，numpy会默认从数组的第一个元素开始。
# 切片时，省去结束值，numpy会默认是数组的最大索引值
# 切片时，省去最后一个数字，numpy默认抽取不考虑间隔
B[:4:2]  

array([10, 12])

In [93]:
B[1::2]

array([11, 13, 15])

In [94]:
B[1:4]

array([11, 12, 13])

二维数组。需要分别指定行和列的索引值

In [97]:
C=np.arange(10,19).reshape((3,3))
C

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [98]:
C[0,:]  # 第二个索引处只使用冒号，而没有指定任意数字，这样选择的是所有列。

array([10, 11, 12])

In [100]:
C[:,0]  #抽取第一列的所有元素

array([10, 13, 16])

In [102]:
# 抽取一个小点儿的矩阵
C[0:2,0:2]  #前0:2表示切第1、2行；后0:2表示切表1、2列

array([[10, 11],
       [13, 14]])

##### 6.3 数组迭代
使用for结构

In [104]:
for i in B:
    print(i)

10
11
12
13
14
15


In [106]:
for row in C:
    print(row)
        

[10 11 12]
[13 14 15]
[16 17 18]


遍历矩阵的每一个元素，用for循环遍历C.flat

In [108]:
for i in C.flat:
    print(i)

10
11
12
13
14
15
16
17
18


用聚合函数处理每一列或行，返回一个数值作为结果。apply_along_axis()函数。

apply_along_axis(聚合函数，axis=对哪条轴应用迭代操作，arr=数组)。如果axis=0按列进行迭代操作，处理元素；axis=1按行进行迭代的操作

In [110]:
np.apply_along_axis(np.mean,axis=0,arr=C)

array([13., 14., 15.])

#### 7、数组操作

##### 7.1 连接数组
将多个数组整合在一起形成一个包含这些数组的新数组

a、连接二维数组

vstack():执行垂直入栈操作，把第二个数组作为行添加到第一个数组，数组朝垂直方向生长。

hstack():执行水平入栈操作，将第二个数组作为列添加到第一个数组

b、连接一维数组

column_stack():把一维数组作为列压入栈结构，形成一个新的二维数组

row_stack():把一维数组作为行压入栈结构，形成一个新的二维数组


In [112]:
D=np.zeros((3,3))
E=np.ones((3,3))
np.vstack((D,E))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [113]:
np.hstack((D,E))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [121]:
d=np.arange(3)
e=np.arange(5,8)
f=np.arange(4,7)
np.column_stack((d,e,f))

array([[0, 5, 4],
       [1, 6, 5],
       [2, 7, 6]])

In [122]:
np.row_stack((d,e,f))

array([[0, 1, 2],
       [5, 6, 7],
       [4, 5, 6]])

##### 7.2 数组切分
水平切分用hsplit( )函数，垂直切分用vsplit( )函数

split()函数：将数组分为几个不对称的部分，指定axis=1:索引为列索引；axis=0，索引为行索引

In [123]:
H=np.arange(16).reshape((4,4))
H

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
[a,b]=np.hsplit(H,2)  # 水平切分数组：把数组按照宽度切分为两部分，4*4变成两个4*2
a

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [129]:
[c,d]=np.vsplit(H,2)  # 垂直切分:把数组按照高度分为两部分，4*4变成两个2*4
d

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
# 将矩阵切分为三部分，第一部分为第一列，第二部分为第二列、第三列，而第三部分为最后一列
[h1,h2,h3]=np.split(H,[1,3],axis=1)
h1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [131]:
h2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [132]:
h3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [134]:
[h1,h2,h3]=np.split(H,[1,2],axis=0)
h1

array([[0, 1, 2, 3]])

In [135]:
h2

array([[4, 5, 6, 7]])

In [136]:
h3

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 8、数组数据文件的读写

save():以二进制格式保存数据； load（）：从二进制文件中读取数据

genfromtxt（存放数据的文件名，delimiter=‘，’用于分隔值的字符，names=True是否含有列标题）